version: '3.7'

services:
  api:
    container_name: budget_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Prevent to override node_modules inside docker container
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    environment:
      DATABASE_HOST: 'database' # Need to set host to the name of the service (database), however we need to set to localhost in .env
    networks:
      - webnet
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  webnet:

volumes:
  pgdata:
