version: '3.7'

services:
  budget_db:
    image: postgres
    container_name: budget_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=budget_app_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: budget_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - budget_db
    depends_on:
      - budget_db
    environment:
      DATABASE_HOST: budget_db
volumes:
  pgdata:
    driver: local
